"""empty message

Revision ID: 47d5110d497d
Revises: 99a4e0cf7f29
Create Date: 2024-06-13 17:51:07.063668

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "47d5110d497d"
down_revision = "99a4e0cf7f29"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usuario", schema=None) as batch_op:
        batch_op.alter_column(
            "senha",
            existing_type=mysql.INTEGER(),
            type_=sa.String(length=20),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usuario", schema=None) as batch_op:
        batch_op.alter_column(
            "senha",
            existing_type=sa.String(length=20),
            type_=mysql.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
