"""empty message

Revision ID: 7cecea9733f2
Revises: 47d5110d497d
Create Date: 2024-06-13 17:55:28.383052

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "7cecea9733f2"
down_revision = "47d5110d497d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usuario", schema=None) as batch_op:
        batch_op.alter_column(
            "cpf_cnpj",
            existing_type=mysql.INTEGER(),
            type_=sa.BigInteger(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usuario", schema=None) as batch_op:
        batch_op.alter_column(
            "cpf_cnpj",
            existing_type=sa.BigInteger(),
            type_=mysql.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
