DEBUG = True

USERNAME = "root"
PASSWORD = "1008981904"
SERVER = "localhost"
DB = "smart_condominium"

SQLALCHEMY_DATABASE_URI = f"mysql://{USERNAME}:{PASSWORD}@{SERVER}/{DB}"
SQLALCHEMY_TRACK_MODIFICATIONS = False
